---
  - name: Install and configure web server
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Install httpd package on all application servers
        yum:
          name: httpd
          state: installed

      - name: Start httpd service
        service:
          name: httpd
          state: started
          enabled: true

      - name: Create blank file and add contents to it
        copy:
          dest: "/var/www/html/index.html"
          content: |
            This is a Nautilus sample file, created using Ansible!

      - name: Adding more info to index.html file
        lineinfile:
          path: /var/www/html/index.html
          line: 'Welcome to Nautilus Group!'
          insertbefore: BOF

      - name: Change file ownership, group and permissions
        file:
          path: /var/www/html/index.html
          owner: apache
          group: apache
          mode: '0644'
